name-template: "v$RESOLVED_VERSION ðŸŒˆ"
tag-template: "v$RESOLVED_VERSION"
prerelease: true
latest: true
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable
header: ""
template: |
    # What's Changed

    $CHANGES

    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
# category-template:
footer: ""
categories:
    - title: "ðŸš€ Features"
      labels:
          - "feature"
          - "enhancement"
    - title: "ðŸ› Bug Fixes"
      labels:
          - "fix"
          - "bugfix"
          - "bug"
    - title: "ðŸ§° Maintenance"
      label: "chore"
    - title: "Documentation"
      label: "type: docs"
    - title: "Other changes"
    - title: "Dependency Updates"
      label: "type: dependencies"
      collapse-after: 5

version-resolver:
    major:
        labels:
            - "major"
    minor:
        labels:
            - "minor"
    patch:
        labels:
            - "patch"
            - "type: bug"
            - "type: maintenance"
            - "type: docs"
            - "type: dependencies"
            - "type: security"

exclude-labels:
    - "skip-changelog"
